#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H

#define BTM_DEF_LOCAL_NAME   "Amazon Fire HD8"

#define BTA_AV_MAX_A2DP_MTU  1788
#define BLE_VND_INCLUDED TRUE
#define BLE_INCLUDED TRUE
#define BTA_GATT_INCLUDED TRUE
#define SMP_INCLUDED TRUE

#endif
